/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokensResponse
 */
export interface AuthTokensResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthTokensResponse
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokensResponse
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AuthTokensResponse interface.
 */
export function instanceOfAuthTokensResponse(value: object): value is AuthTokensResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function AuthTokensResponseFromJSON(json: any): AuthTokensResponse {
    return AuthTokensResponseFromJSONTyped(json, false);
}

export function AuthTokensResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokensResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'refreshToken': json['refreshToken'],
    };
}

export function AuthTokensResponseToJSON(json: any): AuthTokensResponse {
    return AuthTokensResponseToJSONTyped(json, false);
}

export function AuthTokensResponseToJSONTyped(value?: AuthTokensResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'refreshToken': value['refreshToken'],
    };
}

