/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokensResponseBody
 */
export interface AuthTokensResponseBody {
    /**
     * 
     * @type {string}
     * @memberof AuthTokensResponseBody
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokensResponseBody
     */
    refreshToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokensResponseBody
     */
    userName: string;
}

/**
 * Check if a given object implements the AuthTokensResponseBody interface.
 */
export function instanceOfAuthTokensResponseBody(value: object): value is AuthTokensResponseBody {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    return true;
}

export function AuthTokensResponseBodyFromJSON(json: any): AuthTokensResponseBody {
    return AuthTokensResponseBodyFromJSONTyped(json, false);
}

export function AuthTokensResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokensResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'refreshToken': json['refreshToken'],
        'userName': json['userName'],
    };
}

export function AuthTokensResponseBodyToJSON(json: any): AuthTokensResponseBody {
    return AuthTokensResponseBodyToJSONTyped(json, false);
}

export function AuthTokensResponseBodyToJSONTyped(value?: AuthTokensResponseBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'refreshToken': value['refreshToken'],
        'userName': value['userName'],
    };
}

