/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordRequestBody
 */
export interface ChangePasswordRequestBody {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequestBody
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequestBody
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequestBody
     */
    newPassword: string;
}

/**
 * Check if a given object implements the ChangePasswordRequestBody interface.
 */
export function instanceOfChangePasswordRequestBody(value: object): value is ChangePasswordRequestBody {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function ChangePasswordRequestBodyFromJSON(json: any): ChangePasswordRequestBody {
    return ChangePasswordRequestBodyFromJSONTyped(json, false);
}

export function ChangePasswordRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'oldPassword': json['oldPassword'],
        'newPassword': json['newPassword'],
    };
}

export function ChangePasswordRequestBodyToJSON(json: any): ChangePasswordRequestBody {
    return ChangePasswordRequestBodyToJSONTyped(json, false);
}

export function ChangePasswordRequestBodyToJSONTyped(value?: ChangePasswordRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'oldPassword': value['oldPassword'],
        'newPassword': value['newPassword'],
    };
}

