/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageDto
 */
export interface ChatMessageDto {
    /**
     * 
     * @type {number}
     * @memberof ChatMessageDto
     */
    senderId: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDto
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ChatMessageDto interface.
 */
export function instanceOfChatMessageDto(value: object): value is ChatMessageDto {
    if (!('senderId' in value) || value['senderId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ChatMessageDtoFromJSON(json: any): ChatMessageDto {
    return ChatMessageDtoFromJSONTyped(json, false);
}

export function ChatMessageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'senderId': json['senderId'],
        'content': json['content'],
        'timestamp': json['timestamp'],
    };
}

export function ChatMessageDtoToJSON(json: any): ChatMessageDto {
    return ChatMessageDtoToJSONTyped(json, false);
}

export function ChatMessageDtoToJSONTyped(value?: ChatMessageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'senderId': value['senderId'],
        'content': value['content'],
        'timestamp': value['timestamp'],
    };
}

