/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoggedUserDto
 */
export interface LoggedUserDto {
    /**
     * 
     * @type {number}
     * @memberof LoggedUserDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof LoggedUserDto
     */
    lastName: string;
}

/**
 * Check if a given object implements the LoggedUserDto interface.
 */
export function instanceOfLoggedUserDto(value: object): value is LoggedUserDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function LoggedUserDtoFromJSON(json: any): LoggedUserDto {
    return LoggedUserDtoFromJSONTyped(json, false);
}

export function LoggedUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoggedUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
    };
}

export function LoggedUserDtoToJSON(json: any): LoggedUserDto {
    return LoggedUserDtoToJSONTyped(json, false);
}

export function LoggedUserDtoToJSONTyped(value?: LoggedUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

