/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRequestBody
 */
export interface LoginRequestBody {
    /**
     * 
     * @type {string}
     * @memberof LoginRequestBody
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequestBody
     */
    password: string;
}

/**
 * Check if a given object implements the LoginRequestBody interface.
 */
export function instanceOfLoginRequestBody(value: object): value is LoginRequestBody {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginRequestBodyFromJSON(json: any): LoginRequestBody {
    return LoginRequestBodyFromJSONTyped(json, false);
}

export function LoginRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'password': json['password'],
    };
}

export function LoginRequestBodyToJSON(json: any): LoginRequestBody {
    return LoginRequestBodyToJSONTyped(json, false);
}

export function LoginRequestBodyToJSONTyped(value?: LoginRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'password': value['password'],
    };
}

