/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectRequestBody
 */
export interface ProjectRequestBody {
    /**
     * 
     * @type {number}
     * @memberof ProjectRequestBody
     */
    ownerId: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectRequestBody
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRequestBody
     */
    description: string;
}

/**
 * Check if a given object implements the ProjectRequestBody interface.
 */
export function instanceOfProjectRequestBody(value: object): value is ProjectRequestBody {
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ProjectRequestBodyFromJSON(json: any): ProjectRequestBody {
    return ProjectRequestBodyFromJSONTyped(json, false);
}

export function ProjectRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'ownerId': json['ownerId'],
        'title': json['title'],
        'description': json['description'],
    };
}

export function ProjectRequestBodyToJSON(json: any): ProjectRequestBody {
    return ProjectRequestBodyToJSONTyped(json, false);
}

export function ProjectRequestBodyToJSONTyped(value?: ProjectRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ownerId': value['ownerId'],
        'title': value['title'],
        'description': value['description'],
    };
}

