/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAddRequestBody
 */
export interface ProjectAddRequestBody {
    /**
     * 
     * @type {number}
     * @memberof ProjectAddRequestBody
     */
    ownerId: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectAddRequestBody
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectAddRequestBody
     */
    description: string;
}

/**
 * Check if a given object implements the ProjectAddRequestBody interface.
 */
export function instanceOfProjectAddRequestBody(value: object): value is ProjectAddRequestBody {
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ProjectAddRequestBodyFromJSON(json: any): ProjectAddRequestBody {
    return ProjectAddRequestBodyFromJSONTyped(json, false);
}

export function ProjectAddRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAddRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'ownerId': json['ownerId'],
        'title': json['title'],
        'description': json['description'],
    };
}

export function ProjectAddRequestBodyToJSON(json: any): ProjectAddRequestBody {
    return ProjectAddRequestBodyToJSONTyped(json, false);
}

export function ProjectAddRequestBodyToJSONTyped(value?: ProjectAddRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ownerId': value['ownerId'],
        'title': value['title'],
        'description': value['description'],
    };
}

