/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUpdateRequestBody
 */
export interface ProjectUpdateRequestBody {
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateRequestBody
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateRequestBody
     */
    description: string;
}

/**
 * Check if a given object implements the ProjectUpdateRequestBody interface.
 */
export function instanceOfProjectUpdateRequestBody(value: object): value is ProjectUpdateRequestBody {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ProjectUpdateRequestBodyFromJSON(json: any): ProjectUpdateRequestBody {
    return ProjectUpdateRequestBodyFromJSONTyped(json, false);
}

export function ProjectUpdateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdateRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
    };
}

export function ProjectUpdateRequestBodyToJSON(json: any): ProjectUpdateRequestBody {
    return ProjectUpdateRequestBodyToJSONTyped(json, false);
}

export function ProjectUpdateRequestBodyToJSONTyped(value?: ProjectUpdateRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

