/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenRequestBody
 */
export interface RefreshTokenRequestBody {
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenRequestBody
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenRequestBody interface.
 */
export function instanceOfRefreshTokenRequestBody(value: object): value is RefreshTokenRequestBody {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshTokenRequestBodyFromJSON(json: any): RefreshTokenRequestBody {
    return RefreshTokenRequestBodyFromJSONTyped(json, false);
}

export function RefreshTokenRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshTokenRequestBodyToJSON(json: any): RefreshTokenRequestBody {
    return RefreshTokenRequestBodyToJSONTyped(json, false);
}

export function RefreshTokenRequestBodyToJSONTyped(value?: RefreshTokenRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

