/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterRequestBody
 */
export interface RegisterRequestBody {
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestBody
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestBody
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestBody
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestBody
     */
    lastName: string;
}

/**
 * Check if a given object implements the RegisterRequestBody interface.
 */
export function instanceOfRegisterRequestBody(value: object): value is RegisterRequestBody {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function RegisterRequestBodyFromJSON(json: any): RegisterRequestBody {
    return RegisterRequestBodyFromJSONTyped(json, false);
}

export function RegisterRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'email': json['email'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
    };
}

export function RegisterRequestBodyToJSON(json: any): RegisterRequestBody {
    return RegisterRequestBodyToJSONTyped(json, false);
}

export function RegisterRequestBodyToJSONTyped(value?: RegisterRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

