/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAndProjectRequest
 */
export interface UserAndProjectRequest {
    /**
     * 
     * @type {number}
     * @memberof UserAndProjectRequest
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof UserAndProjectRequest
     */
    projectId: number;
}

/**
 * Check if a given object implements the UserAndProjectRequest interface.
 */
export function instanceOfUserAndProjectRequest(value: object): value is UserAndProjectRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    return true;
}

export function UserAndProjectRequestFromJSON(json: any): UserAndProjectRequest {
    return UserAndProjectRequestFromJSONTyped(json, false);
}

export function UserAndProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAndProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'projectId': json['projectId'],
    };
}

export function UserAndProjectRequestToJSON(json: any): UserAndProjectRequest {
    return UserAndProjectRequestToJSONTyped(json, false);
}

export function UserAndProjectRequestToJSONTyped(value?: UserAndProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'projectId': value['projectId'],
    };
}

