/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSimpleDto
 */
export interface UserSimpleDto {
    /**
     * 
     * @type {number}
     * @memberof UserSimpleDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleDto
     */
    lastName: string;
}

/**
 * Check if a given object implements the UserSimpleDto interface.
 */
export function instanceOfUserSimpleDto(value: object): value is UserSimpleDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function UserSimpleDtoFromJSON(json: any): UserSimpleDto {
    return UserSimpleDtoFromJSONTyped(json, false);
}

export function UserSimpleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSimpleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function UserSimpleDtoToJSON(json: any): UserSimpleDto {
    return UserSimpleDtoToJSONTyped(json, false);
}

export function UserSimpleDtoToJSONTyped(value?: UserSimpleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

