/* tslint:disable */
/* eslint-disable */
/**
 * Api V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAndProjectRequestBody
 */
export interface UserAndProjectRequestBody {
    /**
     * 
     * @type {number}
     * @memberof UserAndProjectRequestBody
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof UserAndProjectRequestBody
     */
    projectId: number;
}

/**
 * Check if a given object implements the UserAndProjectRequestBody interface.
 */
export function instanceOfUserAndProjectRequestBody(value: object): value is UserAndProjectRequestBody {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    return true;
}

export function UserAndProjectRequestBodyFromJSON(json: any): UserAndProjectRequestBody {
    return UserAndProjectRequestBodyFromJSONTyped(json, false);
}

export function UserAndProjectRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAndProjectRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'projectId': json['projectId'],
    };
}

export function UserAndProjectRequestBodyToJSON(json: any): UserAndProjectRequestBody {
    return UserAndProjectRequestBodyToJSONTyped(json, false);
}

export function UserAndProjectRequestBodyToJSONTyped(value?: UserAndProjectRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'projectId': value['projectId'],
    };
}

